
name: CICD

on: 
  workflow_dispatch:

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from Github
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container build"
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Test the Container
        run: echo "Testing the Container"
  deploy:
    runs-on: ubuntu-latest
    step:
      - name: Deploying the app
        run: echo "Docker compose deploying the app"
