#This is the name of the workflow that will be displayed in the action tab
name: CICD

# manual click (deliver) workflow whenever user needs
on: 
jobs:
# every jobs needs separte runner is called parallism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode 
        run: echo "Code Clone from Github"
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the container 
        run: echo "Testing the container"
        
  deploy:
    runs-on: ubuntu-latest
    steps:
        name: Deploy the app
        run: echo "Docker compose deployed the app"
